-- MySQL Script generated by MySQL Workbench
-- 11/13/16 14:22:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Office` (
  `Name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NULL,
  `sq_ft` INT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agreement` (
  `ident` INT NOT NULL,
  `cost` INT NULL,
  `endDate` DATE NULL,
  `Office_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ident`, `Office_Name`),
  INDEX `fk_Agreement_Office1_idx` (`Office_Name` ASC),
  CONSTRAINT `fk_Agreement_Office1`
    FOREIGN KEY (`Office_Name`)
    REFERENCES `mydb`.`Office` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agency` (
  `agency_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `phone` VARCHAR(10) NULL,
  PRIMARY KEY (`agency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agency_has_Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agency_has_Agreement` (
  `Agency_agency_id` INT NOT NULL,
  `Agreement_ident` INT NOT NULL,
  PRIMARY KEY (`Agency_agency_id`, `Agreement_ident`),
  INDEX `fk_Agency_has_Agreement_Agreement1_idx` (`Agreement_ident` ASC),
  INDEX `fk_Agency_has_Agreement_Agency1_idx` (`Agency_agency_id` ASC),
  CONSTRAINT `fk_Agency_has_Agreement_Agency1`
    FOREIGN KEY (`Agency_agency_id`)
    REFERENCES `mydb`.`Agency` (`agency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agency_has_Agreement_Agreement1`
    FOREIGN KEY (`Agreement_ident`)
    REFERENCES `mydb`.`Agreement` (`ident`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
