-- Original MySQL Script generated by MySQL Workbench
-- 11/13/16 14:22:41
-- Adapted for Sqlite3 by James Bilbrey

-- -----------------------------------------------------
-- Table `Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Office` (
  `Name` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NULL,
  `sq_ft` INT NULL,
  PRIMARY KEY (`Name`)
);


-- -----------------------------------------------------
-- Table `Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agreement` (
  `ident` INT NOT NULL,
  `cost` INT NULL,
  `endDate` DATE NULL,
  `Office_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ident`),
  FOREIGN KEY (`Office_Name`)
  REFERENCES `Office` (`Name`)
);


-- -----------------------------------------------------
-- Table `Agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agency` (
  `agency_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `phone` VARCHAR(10) NULL,
  PRIMARY KEY (`agency_id`)
);


-- -----------------------------------------------------
-- Table `Agency_has_Agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agency_has_Agreement` (
  `Agency_agency_id` INT NOT NULL,
  `Agreement_ident` INT NOT NULL,
  PRIMARY KEY (`Agency_agency_id`, `Agreement_ident`),
  FOREIGN KEY (`Agency_agency_id`)
  REFERENCES `Agency` (`agency_id`),
  FOREIGN KEY (`Agreement_ident`)
  REFERENCES `Agreement` (`ident`)
);
